FROM mcr.microsoft.com/playwright:v1.51.1-jammy

# Add Microsoft repository and install .NET SDK and PowerShell
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb && \
    dpkg -i packages-microsoft-prod.deb && \
    apt-get update && \
    apt-get install -y dotnet-sdk-8.0 powershell && \
    pwsh --version

# Set the working directory inside the container
WORKDIR /workspace